server:
  port: 8080

spring:
  application:
    name: trading

  datasource:
    url: jdbc:h2:mem:trading
    driverClassName: org.h2.Driver
    username: admin
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


api:
  url:
    binance: https://api.binance.com/api/v3/ticker/bookTicker
    houbi: https://api.huobi.pro/market/tickers